public class Democalc {
        public integer add(integer x, integer y){
            integer z;
            z = x + y;
            return z;
        }
        public integer sub( integer x , integer y ){
            integer z;    
            z = x - y;
            return z;
        }
        public integer mul(integer x , integer y){
            integer z;
            Z = x * y;
            return z;
        }
        
    }